# -*- coding: utf-8 -*-
"""typing_extensions exports"""
from typing_extensions import (
    TYPE_CHECKING,
    ClassVar,
    ContextManager,
    Counter,
    DefaultDict,
    Deque,
    Final,
    Literal,
    NewType,
    NoReturn,
    Protocol,
    Text,
    Type,
    TypeAlias,
    TypedDict,
    final,
    overload,
    runtime_checkable,
)

__all__ = (
    'ClassVar',
    'ContextManager',
    'Counter',
    'DefaultDict',
    'Deque',
    'Final',
    'Literal',
    'NewType',
    'NoReturn',
    'Protocol',
    'TYPE_CHECKING',
    'Text',
    'Type',
    'TypeAlias',
    'TypedDict',
    '__all_typing_extensions__',
    'final',
    'overload',
    'runtime_checkable',
)
__all_typing_extensions__ = __all__
