version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/aiopen"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/asyncify"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/fmts"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/funkify"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/h5"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/jsonbourne"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/lager"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/listless"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/requires"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/shellfish"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/xtyping"
    schedule:
      interval: "daily"
    groups:
      xtyping-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/libs/dgpytest"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  # Last in list b/c it depends on all the others...
  - package-ecosystem: "pip"
    directory: "/libs/dgpylibs"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*"
