version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/libs/aiopen"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/libs/asyncify"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/libs/funkify"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/libs/jsonbourne"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/libs/shellfish"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/libs/xtyping"
    schedule:
      interval: "daily"
