# version: 2
# updates:
# - package-ecosystem: pip
#   directory: "libs/funkify"
#   schedule:
#     interval: weekly
#   open-pull-requests-limit: 10
# - package-ecosystem: pip
#   directory: "libs/aiopen"
#   schedule:
#     interval: weekly
#   open-pull-requests-limit: 10
# - package-ecosystem: pip
#   directory: "libs/requires"
#   schedule:
#     interval: weekly
#   open-pull-requests-limit: 10
# - package-ecosystem: pip
#   directory: "libs/lager"
#   schedule:
#     interval: weekly
#   open-pull-requests-limit: 10
# - package-ecosystem: pip
#   directory: "libs/jsonbourne"
#   schedule:
#     interval: weekly
#   open-pull-requests-limit: 10
