version: 2
updates:
- package-ecosystem: pip
  directory: "/funkify"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/aiopen"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/requires"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
