site_name: dgpy-libs
docs_dir: docs
site_dir: public
site_url: ''
repo_url: 'https://github.com/dynamic-graphics-inc/dgpy-libs/'
repo_name: 'GitHub'
site_author: 'Sheldon & jesse'
copyright: 'Dynamic Graphics Inc'
remote_branch: 'gh-pages'

nav:
  # - Home: './index.md'
  - Libs:
      - Home: './index.md'
      # - aiopen: './libs/aiopen/README.ipynb'
      # - asyncify: './libs/asyncify/README.ipynb'
      # - funkify: './libs/funkify/README.ipynb'
      # - h5: './libs/h5/README.ipynb'
      # - jsonbourne: './libs/jsonbourne/README.ipynb'
      # - lager: './libs/lager/README.ipynb'
      # - requires: './libs/requires/README.ipynb'
      # - xtyping: './libs/xtyping/README.ipynb'
  - API:
      - aiopen: './libs/aiopen/aiopen.api.md'
      - asyncify: './libs/asyncify/asyncify.api.md'
      - fmts: './libs/fmts/fmts.api.md'
      - funkify: './libs/funkify/funkify.api.md'
      - h5: './libs/h5/h5.api.md'
      - requires: './libs/requires/requires.api.md'
      - listless: './libs/listless/listless.api.md'
      - jsonbourne: './libs/jsonbourne/jsonbourne.api.md'
      - shellfish: './libs/shellfish/shellfish.api.md'
      - xtyping: './libs/xtyping/xtyping.api.md'
  # - Notebooks:
  #     - Cache Money: './notebooks/cache_money.ipynb'
  #     - Filter None: './notebooks/filter_none.ipynb'
  #     - JSON "parsing": './notebooks/json_parsing.ipynb'
  #     - String Formatting: './notebooks/string_fmt.ipynb'

theme:
  name: 'material'
  logo: 'images/dgpy_white_edge_small.png'
  favicon: images/favicon.png

  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.top
    - search.highlight

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.escapeall
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem:
      smart_enable: all
  - attr_list
  - toc:
      permalink: ⚓︎

plugins:
  - search:
      lang: en
      # - mkdocs-jupyter:
      # execute: False
  ### MKDOCSTRINGS ###
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - from os import path
            - sys.path.append("docs")
            - sys.path.append(path.join("libs", "aiopen"))
            - sys.path.append(path.join("libs", "asyncify"))
            - sys.path.append(path.join("libs", "dgpylibs"))
            - sys.path.append(path.join("libs", "dgpytest"))
            - sys.path.append(path.join("libs", "fmts"))
            - sys.path.append(path.join("libs", "funkify"))
            - sys.path.append(path.join("libs", "h5"))
            - sys.path.append(path.join("libs", "jsonbourne"))
            - sys.path.append(path.join("libs", "lager"))
            - sys.path.append(path.join("libs", "listless"))
            - sys.path.append(path.join("libs", "shellfish"))
            - sys.path.append(path.join("libs", "xtyping"))
          inherited_members: true
          docstring_style: google
          options:
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            show_source: true
            show_root_heading: true
            show_root_full_path:  false
            show_signature_annotations: true
            show_category_heading: true
            show_root_members_full_path: false
            show_object_full_path: false
            show_if_no_docstring: true
            show_root_toc_entry: true
            heading_level: 2
            # members: true
            filters:
              - "!^_"  # exclude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
            new_path_syntax: false
      watch:
        - libs/aiopen/aiopen
        - libs/jsonbourne/jsonbourne
