site_name: dgpy-libs
docs_dir: docs
site_dir: public
repo_url: 'https://github.com/dynamic-graphics-inc/dgpy-libs/'
repo_name: 'GitHub'
site_author: 'Sheldon'
copyright: 'Dynamic Graphics Inc'
remote_branch: 'gh-pages'
dev_addr: '0.0.0.0:8000'


theme:
  name: 'material'
  logo: 'images/dgpy_white_edge_small.png'
  favicon: 'images/favicon.ico'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    scheme: "slate"
    primary: 'deep-purple'
    accent: 'teal'
  features:
    - tabs
    - instant
    - navigation.instant

markdown_extensions:
  - attr_list

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      selection:
        new_path_syntax: yes
      handlers:
        python:
          rendering:
            show_source: false
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_category_heading: true
      watch:
        - libs/jsonbourne/jsonbourne
        
