site_name: dgpy-libs
docs_dir: docs
site_dir: public
site_url: ''
repo_url: 'https://github.com/dynamic-graphics-inc/dgpy-libs/'
repo_name: 'GitHub'
site_author: 'Sheldon'
copyright: 'Dynamic Graphics Inc'
remote_branch: 'gh-pages'
dev_addr: '0.0.0.0:8000'

nav:
  - Home: './index.md'
  - Libs:
      - aiopen: './libs/aiopen/README.ipynb'
      - asyncify: './libs/asyncify/README.ipynb'
      - funkify: './libs/funkify/README.ipynb'
      - h5: './libs/h5/README.ipynb'
      - jsonbourne: './libs/jsonbourne/README.ipynb'
      - lager: './libs/lager/README.ipynb'
      - requires: './libs/requires/README.ipynb'
      - xtyping: './libs/xtyping/README.ipynb'
  - API:
      - aiopen: './libs/aiopen/api/aiopen.md'
  - Notebooks:
      - Cache Money: './notebooks/cache_money.ipynb'
      - Filter None: './notebooks/filter_none.ipynb'
      - JSON "parsing": './notebooks/json_parsing.ipynb'
      - String Formatting: './notebooks/string_fmt.ipynb'

theme:
  name: 'material'
  logo: 'images/dgpy_white_edge_small.png'
  favicon: images/favicon.png

  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'deep-purple'
    accent: 'teal'
  features:
    - instant
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.top


markdown_extensions:
  - pymdownx.escapeall
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
  - attr_list
  - toc:
      permalink: ⚓︎

plugins:
  - search
  - mkdocs-jupyter:
      execute: False

  ### MKDOCSTRINGS ###
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
          inherited_members: true
          docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_category_heading: true
            show_root_members_full_path: true
            show_object_full_path: true
            show_if_no_docstring: true
            show_root_toc_entry: true
            heading_level: 2
          selection:
            members: true
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
            new_path_syntax: false
      watch:
        - libs/aiopen/aiopen
        - libs/jsonbourne/jsonbourne
