target-version = "py311"
line-length = 88
preview = true

[lint]
select = [
  "ANN",    # annotations
  "B",      # bugbear
  "C4",     # comprehensions
  "D",      # pydocstyle
  "E",      # pyflakes errors
  "EM102",  # f-string-in-exception
  "EM103",  # dot-format-in-exception
  "ERA001", # erradicate
  "F",      # pyflakes warnings
  "FA102",  # require `from __future__ import annotations`
  "FBT",    # flake8-boolean-trap
  "I",      # isort
  "ICN",
  "PIE",    # flake8-pie
  "PLE",    # pylint errors
  "PT",     # flake8-pytest-style
  "Q",      # flake8-quotes
  "RET",    # flake8-return
  "RUF",    # ruff
  "SIM",    # flake8-simplify
  "T201",   # print
  "TC",     # flake8-type-checking
  "TID",    # flake8-tidy-imports
  "UP",     # flake8-pyupgrade
  "W",      # pyflakes warnings
  "YTT",    # flake8-2020
  # -- TODO --
  # "EM101",  # raw-string-in-exception
  # "N",
  # "PLW",
  # "PLR",
]
ignore = [
  "ANN401", # use of Any
  "C417",   # super annoying
  "C901",   # too complex
  "RUF052", # used-dummy-variable
  # PYDOCSTYLE
  "D100", # undocumented-public-module
  "D101", # undocumented-public-class
  "D102", # undocumented-public-method
  "D103", # undocumented-public-function
  "D104", # undocumented-public-package
  "D105", # undocumented-magic-method
  "D107", # undocumented-public-init
  "D403", # first-line-capitalized
  "D415", # first line should end with a period/exclamation point
  "E501", # line too long,
  "FA",
  # PIE
  "PIE804", # unnecessary-dict-kwargs -- TODO: revisit?
  "SIM105", # suppressible-exception
  "SIM115", # open-file-with-context-handler
  # PYUPGRADE
  "UP009", # utf-8 encoding declaration (not needed but I am nostalgic)
  "UP022", # must test shellfish first...
]

[lint.per-file-ignores]
"**/conftest.py" = ["D"]
"**/noxfile.py" = ["D"]
"**/tests/*.py" = [
  "ANN401", # use of Any
  "D1",
  "D100",   # missing docstring in public module
  "D102",
  "D103",   # missing docstring
  "S101",   # use of assert
]
"*.ipynb" = ["ANN", "E741", "F401", "F811", "F821", "RUF031", "T201"]
"libs/jsonbourne/src/jsonbourne/trydantic.py" = [
  "I001", # isort something wrong with in try block import
]
"libs/requires/tests/test_requires.py" = [
  "F821", # undefined name; not valid for this test file
]
"libs/requires/tests/test_requires_w_json_libs.py" = [
  "F821", # undefined name; not valid for this test file
]
"libs/shellfish/tests/*" = [
  "D100", # missing docstring
]

[lint.flake8-errmsg]
max-string-length = 20

[lint.isort]
combine-as-imports = true
known-first-party = [
  "aiopen",
  "asyncify",
  "dgpylibs",
  "dgpytest",
  "fmts",
  "funkify",
  "h5",
  "jsonbourne",
  "lager",
  "listless",
  "requires",
  "shellfish",
  "xtyping",
]
lines-after-imports = -1
lines-between-types = 1

[lint.flake8-boolean-trap]
extend-allowed-calls = ["pydantic.Field"]
[lint.mccabe]
max-complexity = 20

[lint.pydocstyle]
convention = "google"
