name: uv-update-bot

on:
  workflow_dispatch:
  # Set the schedule, for example every week at 8:00am on Monday
  schedule:
    - cron: 0 8 * * 4

permissions:
  contents: write
  pull-requests: write

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: update-uv-lock
        id: update-uv-lock
        run: |
          {
            echo '```text'
            uv lock -U 2>&1
            echo '```'
          } > uv_output.md 
      
      - name: Check if uv.lock changed
        id: check-uv-lock
        run: |
          if [[ -z $(git status --porcelain uv.lock) ]]; then
            echo "No changes to uv.lock"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in uv.lock"
            echo "== uv.lock changes ==" 
            cat uv_output.md
            echo "~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        if: steps.check-uv-lock.outputs.changed == 'true'
        with:
          token: ${{ secrets.SHELDON_GITHUB_ACTIONS_TOKEN }}
          commit-message: Update uv lockfile dependencies
          title: Update dependencies in uv.lock
          body-path: uv_output.md
          branch: update-uv
          base: main
          labels: install
          delete-branch: true
          add-paths: uv.lock
